//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceRecognitionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        public int id { get; set; }
        public int Enrollment_ID { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Privilege { get; set; }
        public string Enabled { get; set; }
    }
}
